app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask_login import UserMixin, AnonymousUserMixin
from flask import current_app, request
from sqlalchemy.orm import relationship
from . import db, login_manager
from alembic import op

class Users(UserMixin, db.Model):
  __tablename__ = 'users'
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(256))
  username = db.Column(db.String(256))
  email = db.Column(db.String(64), unique=True, index=True)
  password_hash = db.Column(db.String(128))
  key = db.Column(db.String(64))

  @property
  def password(self):
    raise AttributeError('password is not a readable attribute')

  @password.setter
  def password(self, password):
    self.password_hash = generate_password_hash(password)

  def verify_password(self, password):
    return check_password_hash(self.password_hash, password)

@login_manager.user_loader
def load_user(user_id):
  return Users.query.get(int(user_id))

class Records(db.Model):
  __tablename__ = 'records'
  id = db.Column(db.Integer, primary_key=True)
  hash = db.Column(db.String(256))
  date = db.Column(db.Text)
  book = db.Column(db.String(256))
  owner = db.Column(db.Integer, db.ForeignKey('users.id'))
  note = db.Column(db.Text)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField, SubmitField, IntegerField, FileField, PasswordField, DateField
from wtforms.validators import DataRequired, Length, Email, Regexp, EqualTo
from wtforms import ValidationError
from datetime import date, time, timedelta
from time import strptime
import datetime

class CreateBook(FlaskForm):
  new_book = StringField('New Book')
  submit = SubmitField('Create')

class WriteNotes(FlaskForm):
  note_input = TextAreaField('Enter a note')
  submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from config import config
from flask_login import LoginManager

bootstrap = Bootstrap()
moment = Moment()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app(config_name):
  app = Flask(__name__)
  app.config.from_object(config[config_name])
  config[config_name].init_app(app)

  bootstrap.init_app(app)
  moment.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)

  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint, url_prefix='/auth')

  return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, redirect, url_for, abort, flash
from flask_login import login_required, current_user
from . import main
from .. import db
from time import strptime
import datetime
from sqlalchemy import extract, desc
from dateutil.relativedelta import relativedelta
from ..models import Users, Records
import hashlib as hasher
import os
import gnupg
from markdown2 import Markdown
from .forms import WriteNotes, CreateBook

# Define what a notes block is
class Block:
  def __init__(self, index, timestamp, data, previous_hash):
    self.index = index
    self.timestamp = timestamp
    self.data = data
    self.previous_hash = previous_hash
    self.hash = self.hash_block()
  
  def hash_block(self):
    sha = hasher.sha256()
    sha.update(str(self.index) + str(self.timestamp) + str(self.data) + str(self.previous_hash))
    return sha.hexdigest()

class getBooks:
  def __init__(self):
    notebooks = []
    notebooks_db_objects = Records.query.filter_by(owner = current_user.name).group_by(Records.book).all()
    for notebook_db_object in notebooks_db_objects:
      notebooks.append(notebook_db_object.book)
    self.books = notebooks

# Standard routes
@main.route('/', methods=['GET', 'POST'])
@login_required
def index():

  # Check if genesis block exists
  first_block = Records.query.filter_by(id = 1).first()
  if first_block is None:
    now = datetime.datetime.now()
    genesis_hash = Block(1, now, 'Genesis Block', "0").hash

    genesis_block = Records(hash = genesis_hash, date = now, note = 'Genesis Block')
    db.session.add(genesis_block)
    db.session.commit()

    flash('Blockchain initiated: Genesis hash ' + genesis_hash + ' created at ' + str(now))

  # Check whether private/public key exists
  if not os.path.exists('/home/' + Users.query.filter_by(name = current_user.name).first().username + '/.gnupg'):
    flash('Please create some gpg keys')

  form = CreateBook()
  if form.validate_on_submit():
    return redirect(url_for('main.notebook', book=form.new_book.data))

  return render_template('index.html', form=form, notebooks=getBooks().books)

@main.route('/about')
def about():
  return render_template('about.html', notebooks=getBooks().books)

@main.route('/health')
def health():
  return 'running'

@main.route('/notebook/<book>/', methods=['GET', 'POST'])
def notebook(book):
  gpg = gnupg.GPG(gnupghome='/home/' + Users.query.filter_by(name = current_user.name).first().username + '/.gnupg')

  note_db_objects = Records.query.filter_by(book=book).all()
  
  notes = ''
  for note_data in note_db_objects:

    decrypted_data = gpg.decrypt(note_data.note)

    markdowner = Markdown()
    html_data = markdowner.convert(str(decrypted_data))

    notes = notes + "<p align=right><b>" + str(note_data.date) + "</b></p>" + html_data

  presentation_notebook = 'Testing'

  form = WriteNotes()
  if form.validate_on_submit():
    data = form.note_input.data
    key = Users.query.filter_by(name = current_user.name).first().key
    encrypted_ascii_data = gpg.encrypt(data, key, sign=True)

    previous_hash_object = Records.query.order_by(Records.id.desc()).first()
    id = previous_hash_object.id + 1
    now = datetime.datetime.now()
    old_hash = previous_hash_object.hash

    new_hash = Block(id, now, encrypted_ascii_data, old_hash).hash

    new_block = Records(hash = new_hash, date = now, book = book, owner = current_user.name, note = str(encrypted_ascii_data))
    db.session.add(new_block)
    db.session.commit()
    print('Hash: ' + new_hash + ' has been recorded')

    return redirect(url_for('main.notebook', book = book))

  return render_template('notebook.html', notebooks = getBooks().books, presentation_notebook = notes, form = form)

## Run in virtualenvironment
#activate_this_file = "venv/bin/activate_this.py"
#execfile(activate_this_file, dict(__file__=activate_this_file))
#
#from flask import Flask
#from flask import request
#import json
#import requests
#import hashlib as hasher
#import datetime as date
#import os
#from optparse import OptionParser
#from os.path import expanduser
#import git
#import subprocess
#import webbrowser
#import time
#

#
#  # Calculate hash and add to record
#  now=date.datetime.now()
#  new_hash=Block(id, now, file_data, old_hash).hash
#
#  records_file=open(home + "/.bcnotes/data/records", "a+")
#  records_file.write(str(id) + "," + str(now) + "," + new_hash + "\n")
#  records_file.close()
#
#  print("Recorded hash: " + new_hash)
#
#  # Commit to git repo
#  repo_dir = os.path.join(home + "/.bcnotes/data")
#  file_name = os.path.join(repo_dir, str(id) + '.asc')
#  records_file_git = os.path.join(repo_dir, "records")
#
#  r = git.Repo.init(repo_dir)
#  r.index.add([file_name, records_file_git])
#  r.index.commit("Commit index: " + str(id))
#
#  print("Commited index: " + str(id))

app/templates/about.html
{% extends "base.html" %}

{% block title %}Notebook{% endblock %}

{% block page_content %}
<div class="container">
  <div class="page-header">
    <h1>About the Notebook App</h1>
    <p>Well written handwritten notebooks are advantageous over digital versions because they are far harder to fake reliably, and can provide a useful and truthful history - complete with crossings out and mistakes. This project intends to make use of encryption and blockchain to make a reliable and secure digital notebook.</p>
    <h3>Attributions</h3>
    <ul>
      <li>My wife and father-in-law, for their patience and help</li>
    </ul>
  </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Notebook{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Notebook</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Choose Notebook<b class="caret"></b></a>
                  <ul class="dropdown-menu">
                  {% for book in notebooks %}
                    {% if book is not none %}
                      <li><a href="{{ url_for('main.notebook', book=book) }}">{{ book }}</a></li>
                    {% endif %}
                  {% endfor %}
                  </ul>
                </li>
                {% endif %}
                <li><a href="{{ url_for('main.about') }}">About</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if current_user.is_authenticated %}
              <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
              {% else %}
              <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
              {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Notebook{% endblock %}

{% block page_content %}
{% import "bootstrap/wtf.html" as wtf %}
Notes!
<div class="col-md-4">
  {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/notebook.html
{% extends "base.html" %}

{% block title %}Notebook{% endblock %}

{% block page_content %}
{% import "bootstrap/wtf.html" as wtf %}
<div class="container">
  <div class="page-header">
    {{ presentation_notebook|safe }}
  </div>
</div>
<div class="col-md-4">
  {{ wtf.quick_form(form) }}
</div>
{% endblock %}